version: "2.0"
services:
  spacedeck:
    image: kroschu/whiteboard-arm:latest
    restart: always
    ports:
      - "9666:9666"
    volumes:
      - ./storage:/app/storage
      - ./database:/app/database
